// File: bfm.v
// Generated by MyHDL 0.11
// Date: Mon Aug  7 05:41:40 2023


`timescale 1ns/1ps

module bfm (
    clk,
    res_o
);
// bfm
// 
// res_o -- output

input clk;
output [7:0] res_o;
reg [7:0] res_o;

reg [7:0] A_s;
reg [7:0] B_s;
reg [1599:0] data;
reg [6:0] num;
reg reset;
reg xmit_en;



initial begin: BFM_STIMULUS
    integer i;
    reset <= 1;
    for (i=0; i<10; i=i+1) begin
        @(posedge clk);
    end
    reset <= 0;
end


always @(posedge clk) begin: BFM_ADD
    if (reset) begin
        A_s <= 0;
        B_s <= 0;
        num <= 0;
    end
    else begin
        if (xmit_en) begin
            A_s <= data[8-1:0];
            B_s <= data[16-1:8];
            data <= (data >>> 16);
            num <= (num + 1);
        end
        if ((num >= 100)) begin
            num <= 0;
            xmit_en <= 0;
        end
    end
end


MyTopLevel dut(
    A_s,
    B_s,
    res_o,
    clk,
    reset_i
);

endmodule
