// File: bfm.v
// Generated by MyHDL 0.11
// Date: Sun Aug  6 06:51:46 2023


`timescale 1ns/1ps

module bfm (
    res_o
);
// bfm
// 
// res_o -- output

output [15:0] res_o;
reg [15:0] res_o;

reg [7:0] A_s;
reg [7:0] B_s;
reg clk_i;
reg [2399:0] data;
reg [6:0] num;
reg [2:0] op_s;
reg reset_i;
reg start;
reg xmit_en;



initial begin: BFM_CLKDRIVER0_DRIVE_CLK
    while (1'b1) begin
        # 5;
        clk_i <= 1;
        # 5;
        clk_i <= 0;
    end
end


initial begin: BFM_STIMULUS
    integer i;
    reset_i <= 0;
    for (i=0; i<10; i=i+1) begin
        @(posedge clk_i);
    end
    reset_i <= 1;
end


always @(posedge clk_i) begin: BFM_ADD
    if ((!reset_i)) begin
        A_s <= 0;
        B_s <= 0;
        op_s <= 0;
        start <= 0;
        num <= 0;
    end
    else begin
        if (xmit_en) begin
            op_s <= data[3-1:0];
            A_s <= data[16-1:8];
            B_s <= data[24-1:16];
            start <= 1;
            data <= (data >>> 24);
            num <= (num + 1);
        end
        if ((num >= 100)) begin
            num <= 0;
            xmit_en <= 0;
        end
    end
end


tinyalu dut(
    clk_i,
    A_s,
    B_s,
    op_s,
    reset_i,
    start,
    done,
    res_o
);

endmodule
