// File: bfm.v
// Generated by MyHDL 0.11
// Date: Sun Aug  6 06:51:46 2023


`timescale 1ns/1ps

module bfm (

);



reg io_output_ready;
wire io_output_valid;
wire io_input_ready;
wire io_output_last;
wire [254:0] io_output_payload;
reg clk;
reg [7649:0] data;
reg [1:0] i;
reg io_input_last;
reg [254:0] io_input_payload;
reg io_input_valid;
reg [4:0] num;
reg resetn;
reg xmit_en;



initial begin: BFM_CLKDRIVER0_DRIVE_CLK
    while (1'b1) begin
        # 5;
        clk <= 1;
        # 5;
        clk <= 0;
    end
end


always @(posedge clk) begin: BFM_HASH
    if ((!resetn)) begin
        xmit_en <= 0;
        i <= 0;
        num <= 0;
        io_input_valid <= 0;
        io_input_last <= 0;
        io_input_payload <= 0;
    end
    else begin
        if (xmit_en) begin
            io_input_valid <= 1;
            num <= (num + 1);
            io_input_payload <= data[255-1:0];
            i <= (i + 1);
            if ((i == 2)) begin
                io_input_last <= 1;
                i <= 0;
            end
            else begin
                io_input_last <= 0;
            end
            data <= (data >>> 255);
        end
        if (($signed({1'b0, num}) >= (30 - 1))) begin
            num <= 0;
            xmit_en <= 0;
        end
        if ((!xmit_en)) begin
            io_input_valid <= 0;
        end
    end
end


PoseidonTopLevel dut(
    io_input_valid,
    io_input_ready,
    io_input_last,
    io_input_payload,
    io_output_valid,
    io_output_ready,
    io_output_last,
    io_output_payload,
    clk,
    resetn
);

endmodule
